### ISSUE TITLE
Request-URI Too Large

### ISSUE THREAD

**Issue by gmcmicken** [jolicode/slack-php-api#111]
Some API methods such as views.publish require a large payload and as a result - can fail with `Request-URI Too Large`. Is there a way to have the client send as HTTP POST with either form values or JSON encoded body? Slack API supports both of these options. [Using the Slack Web API](https://api.slack.com/web)

**Comment by damienalexandre** [comment]
Slack document this method as "GET": 

https://github.com/jolicode/slack-php-api/blob/65ae9fd575899f0fe6eae4d16595e49940c1261a/resources/slack-openapi.json#L22870-L22961

Because https://github.com/slackapi/slack-api-specs has so much issues, we have a patch system in place to edit the specification when needed. But this change would be a big one, may I suggest you open an issue on https://github.com/slackapi/slack-api-specs too?

Also here is the documentation about our patch system https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md is you wanna submit a PR about this :wink: 

Thanks a lot

**Comment by gmcmicken** [comment]
No sorry I didn't have the time to pursue this one. Thanks @ryneandal
