### ISSUE TITLE
How to get the exact error messages

### ISSUE THREAD

**Issue by iveto89** [jolicode/slack-php-api#7]
I want to check the exact error code. This is what I receive as `$response` when trying to get users list:
`$response = $this->slackClient->usersList();`
```JoliCode\Slack\Api\Model\UsersListGetResponse200 Object
        (
            [cacheTs:protected] => 
            [members:protected] => 
            [ok:protected] => 
            [responseMetadata:protected] => 
            [storage:ArrayObject:private] => Array
                (
                    [error] => invalid_auth
                )

        )```

How should specific errors be handled such as `account_inactive`, `invalid_auth` etc?

**Comment by pyrech** [comment]
The last parameter of all endpoint methods (aka `$fetch`) allow you to change the return value. If you specify the constant `Jane\OpenApiRuntime\Client\Client::FETCH_RESPONSE`, then the method will return the PSR7 response instead of the resource. Example:

```
$response = $this->slackClient->usersList([], Client::FETCH_RESPONSE);
var_dump($response->getStatusCode());
```

I'm not sure what would be the best way to handle such errors. Maybe a Httplug plugin added to the  PluginClient could allow to have a generic solution. If you manage to get some good stuff to handle those errors, do not hesitate to ping us back, so we can either add your work to the library or at least mention it in the documentation.

Cheers!

**Comment by iveto89** [comment]
Won't it be easier to expose this data to be public? In this way it returns PSR7 response and I have to call the method twice in order to fetch the actual data.

**Comment by pyrech** [comment]
Yes but to make it public, we would need to edit the OpenAPI spec of all API's endpoints. But, our goal is to stay as close as possible of the original spec, not to maintain a fork of it with a lot of changes.

I really think a custom Httplug plugin would be the right option for us as, for every Slack response, it could automatically detects if there is a Slack error and throw an exception in this case.

I will try to give it a look if nobody worked on this, but do not expect it before few weeks :wink:

**Comment by jamesgraham** [comment]
@pyrech is this something still on your roadmap?

**Comment by pyrech** [comment]
ATM I only tried the idea I had about using a Httplug plugin. I realized that it would require to access the unserialized response's content before passing it to the serializer, so probably a no-go. I didn't give it another try since.

Yes I still would like to fix this issue, but do not have a lot of time currently. If someone else finds a solution, please open a PR or comment in this ticket :wink: 

Cheers :beers:

**Comment by pyrech** [comment]
Hello @iveto89,

I finally got time to fix this issue. I just opened #56 as a proposal to fix this issue. Could you give a look and report if it fits your need?

Thanks
